Modify readme to explain behaviour when encountering region-blocked videos and clarified date cutoffs
TheFrenchGhosty/TheFrenchGhostys-YouTube-DL-Archivist-Scripts pull request #36
Opened 2021-02-03 15:30 UTC by 93-infinity

2021-02-03 17:09 UTC, TheFrenchGhosty requested changes

2021-02-03 17:09 UTC, TheFrenchGhosty commented on README.md
> +Archive Scripts: Scripts that will download everything that was created before December 31 of the previous year, inclusive. For example, if the current date is any day between 2021-01-01 and 2021-12-
inclusive > included

2021-02-03 17:09 UTC, TheFrenchGhosty commented on README.md
> +Active Scripts: Scripts that will download everything that was created after January 1 of the current year, inclusive. For example, if the current date is 2021-02-02, everything created between and d
inclusive > included

2021-02-03 17:09 UTC, TheFrenchGhosty commented on README.md
> +Using a VPN, switch between US and Germany. Or in general: if you follow a specific country's content, switch to that country (e.g. switch to France if you follow French content)
Replace with:

Using a VPN, switch between US and Germany, and if you follow a specific country's content, also switch to that country (e.g. switch to France if you follow French content).

2021-02-04 03:05 UTC, 93-infinity commented on README.md
> +Archive Scripts: Scripts that will download everything that was created before December 31 of the previous year, inclusive. For example, if the current date is any day between 2021-01-01 and 2021-12-
pls clarify, I don't understand

2021-02-06 02:01 UTC, closed without merging